[build]
  base = "hr-diagram-app"
  publish = "build"
  command = "export NODE_OPTIONS=--openssl-legacy-provider && npm install && npm run build"

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"